/* Zingers prompt bank. Add your own: one string per line, keep them short and open-ended. */
window.ZINGERS_PROMPTS = {
  clean: [
    "A terrible name for a retirement home",
    "The real reason the dinosaurs went extinct",
    "What your houseplant says about you behind your back",
    "The worst thing to find in a hotel room drawer",
    "A rejected flavour of toothpaste",
    "The one-star review a ghost leaves for a haunted house",
    "Something you should never whisper during a job interview",
    "What cats are actually plotting",
    "The worst possible slogan for an airline",
    "A new Olympic sport nobody asked for",
    "The least comforting thing a surgeon can say mid-operation",
    "A terrible theme for a child's birthday party",
    "The fine print on a cheap gym membership",
    "An unhelpful message inside a fortune cookie",
    "The worst possible wedding vow",
    "A superhero with an extremely specific power",
    "The most suspicious thing to buy at 3 a.m.",
    "A self-help book title that would make things worse",
    "The worst excuse for being late to your own wedding",
    "What your fridge would say if it could talk",
    "A law that only benefits one weirdly specific person",
    "The last thing you want to hear from your therapist",
    "A rejected name for a newly discovered planet",
    "A text you should never send to your boss",
    "What the office printer is really thinking",
    "The worst thing a tour guide can say at the Grand Canyon",
    "A candle scent that should not exist",
    "The real reason your neighbour installed a doorbell camera",
    "A bad name for a meditation app",
    "What pigeons discuss in their weekly meeting",
    "The worst thing to say when meeting your partner's parents",
    "A LinkedIn skill nobody should endorse",
    "The worst possible out-of-office reply",
    "What the Wi-Fi password is at a very unwelcoming cafe",
    "A feature your phone really doesn't need",
    "The real reason the meeting could have been an email",
    "A terrible name for a boat",
    "The worst item to bring to a potluck",
    "A rejected Pixar movie",
    "What your dog would put on its CV",
    "The worst thing to hear from the cockpit",
    "An IKEA product that should be recalled",
    "The least reassuring sign on a rollercoaster",
    "The worst possible name for a dating app",
    "A new holiday that nobody would celebrate",
    "The most passive-aggressive note left on a shared fridge",
    "A sequel that should never have been made",
    "What a goldfish is thinking during its three-second memory",
    "The worst thing to shout at a silent retreat",
    "A crime that should exist but doesn't",
    "The worst reason to call in sick",
    "A terrible motto for a hospital",
    "What your GPS says when it has finally had enough",
    "The worst thing a magician can pull out of a hat",
    "An autocorrect that ruined a funeral",
    "A useless item in a survival kit",
    "The worst thing to hear from your hairdresser",
    "The secret ingredient in cafeteria mystery meat",
    "A new crayon colour for disappointed children",
    "The most boring superhero origin story",
    "What the moon thinks of us",
    "The worst name for a perfume",
    "What your smart speaker hears when you're not home",
    "A terrible title for a children's book",
    "The real reason socks go missing in the laundry",
    "A bad question to ask on a first date",
    "The worst thing to find in your burrito",
    "A new rule for the office kitchen",
    "Something a pirate would complain about on social media",
    "The worst possible karaoke song to sing at a funeral",
    "What robots will be embarrassed about in 100 years",
    "A terrible name for a band of accountants",
    "The worst thing to say during a eulogy",
    "The worst possible welcome mat message",
    "A startup idea that should not get funded",
    "The worst thing to have tattooed on your forehead",
    "The one thing you should never Google at work",
    "A snack only a villain would eat",
    "The worst sound to hear during a massage",
    "What your group chat is secretly named without you",
    "An inspirational quote that is not inspiring at all",
    "The worst thing a waiter can say after you order",
    "A board game nobody wants to play",
    "What squirrels are really burying",
    "The worst name for a newborn baby",
    "A terrible first line for a novel",
    "The real reason the chicken crossed the road",
    "What your cat does when you leave for work",
    "The worst possible school field trip",
    "A job title that sounds made up",
    "The worst thing to say on a video call before you realise you're unmuted",
    "What's really in the Bermuda Triangle",
    "A tourist attraction nobody visits twice",
    "A terrible opening line for a TED talk",
    "The worst thing to find under your bed",
    "A rejected emoji",
    "An app notification you never want to see",
    "The worst thing to say to a police horse",
    "A reality TV show that should be cancelled immediately",
    "What the Mona Lisa is actually smiling about",
    "The worst item to pack for a beach holiday",
    "A new flavour of crisps that failed spectacularly",
    "The worst thing your landlord can text you",
    "A very specific phobia",
    "What aliens think the pyramids were for",
    "A terrible name for a hair salon",
    "The worst advice a grandparent ever gave",
    "An awkward thing to say in a lift",
    "The worst name for a restaurant",
    "What the tooth fairy does with all those teeth",
    "A terrible prize at a school raffle",
    "What your laptop fan is trying to tell you",
    "A sport that would be improved by adding bees",
    "The worst motivational poster for an office",
    "What your future self is texting you right now",
    "A terrible name for a political party",
    "The worst thing to say at a baby shower"
  ],
  cheeky: [
    "The least romantic thing to whisper in bed",
    "What your search history says about you",
    "A terrible pickup line for a funeral",
    "The worst thing to hear on a first date after the second drink",
    "A rejected Tinder bio",
    "What happens at the office party that stays at the office party",
    "The worst name for a lingerie brand",
    "What your ex is doing right now",
    "A walk of shame excuse that nobody believes",
    "The worst thing to accidentally send to the family group chat",
    "A drinking game that should be illegal",
    "The worst thing to find in your partner's browser history",
    "What the neighbours heard last night",
    "The worst safe word",
    "A terrible thing to moan during a massage",
    "Something you should never say during a hangover brunch",
    "The worst thing to say right after a kiss",
    "A cocktail name that should get the bartender fired",
    "The real reason for the stag do disaster",
    "What your mum found in your room",
    "A hen party activity that went too far",
    "The worst thing to hear through hotel walls",
    "An honest name for a nightclub",
    "What the bouncer is really thinking",
    "The worst excuse for not texting back",
    "A dating app filter that really should exist",
    "The worst place to get caught skinny dipping",
    "What really goes on at a book club",
    "The worst thing to say to a date's roommate at 7 a.m.",
    "A flirting technique that has never once worked"
  ],
  finals: [
    "The title of your future autobiography",
    "What aliens will write in their report about humans",
    "The secret ingredient in grandma's famous recipe",
    "The first rule of the group chat",
    "Your honest review of this game night",
    "What will be written on your tombstone",
    "The name of your future pub",
    "The worst thing to hear from the person next to you on a 12-hour flight",
    "The headline if you became famous tomorrow",
    "A confession you'd make only on your last day on Earth",
    "The fourth wise man's gift",
    "Your villain origin story in one sentence",
    "What you would ban if you ruled the world for a day",
    "The last text you'd send before the zombie apocalypse",
    "Your warning label",
    "The name of the documentary about your life"
  ]
};
