/* Zingers prompt bank. Add your own: one string per line, keep them short and open-ended. */
window.ZINGERS_PROMPTS = {
  clean: [
    "A terrible name for a retirement home",
    "The real reason the dinosaurs went extinct",
    "What your houseplant says about you behind your back",
    "The worst thing to find in a hotel room drawer",
    "A rejected flavour of toothpaste",
    "The one-star review a ghost leaves for a haunted house",
    "Something you should never whisper during a job interview",
    "What cats are actually plotting",
    "The worst possible slogan for an airline",
    "A new Olympic sport nobody asked for",
    "The least comforting thing a surgeon can say mid-operation",
    "A terrible theme for a child's birthday party",
    "The fine print on a cheap gym membership",
    "An unhelpful message inside a fortune cookie",
    "The worst possible wedding vow",
    "A superhero with an extremely specific power",
    "The most suspicious thing to buy at 3 a.m.",
    "A self-help book title that would make things worse",
    "The worst excuse for being late to your own wedding",
    "What your fridge would say if it could talk",
    "A law that only benefits one weirdly specific person",
    "The last thing you want to hear from your therapist",
    "A rejected name for a newly discovered planet",
    "A text you should never send to your boss",
    "What the office printer is really thinking",
    "The worst thing a tour guide can say at the Grand Canyon",
    "A candle scent that should not exist",
    "The real reason your neighbour installed a doorbell camera",
    "A bad name for a meditation app",
    "What pigeons discuss in their weekly meeting",
    "The worst thing to say when meeting your partner's parents",
    "A LinkedIn skill nobody should endorse",
    "The worst possible out-of-office reply",
    "What the Wi-Fi password is at a very unwelcoming cafe",
    "A feature your phone really doesn't need",
    "The real reason the meeting could have been an email",
    "A terrible name for a boat",
    "The worst item to bring to a potluck",
    "A rejected Pixar movie",
    "What your dog would put on its CV",
    "The worst thing to hear from the cockpit",
    "An IKEA product that should be recalled",
    "The least reassuring sign on a rollercoaster",
    "The worst possible name for a dating app",
    "A new holiday that nobody would celebrate",
    "The most passive-aggressive note left on a shared fridge",
    "A sequel that should never have been made",
    "What a goldfish is thinking during its three-second memory",
    "The worst thing to shout at a silent retreat",
    "A crime that should exist but doesn't",
    "The worst reason to call in sick",
    "A terrible motto for a hospital",
    "What your GPS says when it has finally had enough",
    "The worst thing a magician can pull out of a hat",
    "An autocorrect that ruined a funeral",
    "A useless item in a survival kit",
    "The worst thing to hear from your hairdresser",
    "The secret ingredient in cafeteria mystery meat",
    "A new crayon colour for disappointed children",
    "The most boring superhero origin story",
    "What the moon thinks of us",
    "The worst name for a perfume",
    "What your smart speaker hears when you're not home",
    "A terrible title for a children's book",
    "The real reason socks go missing in the laundry",
    "A bad question to ask on a first date",
    "The worst thing to find in your burrito",
    "A new rule for the office kitchen",
    "Something a pirate would complain about on social media",
    "The worst possible karaoke song to sing at a funeral",
    "What robots will be embarrassed about in 100 years",
    "A terrible name for a band of accountants",
    "The worst thing to say during a eulogy",
    "The worst possible welcome mat message",
    "A startup idea that should not get funded",
    "The worst thing to have tattooed on your forehead",
    "The one thing you should never Google at work",
    "A snack only a villain would eat",
    "The worst sound to hear during a massage",
    "What your group chat is secretly named without you",
    "An inspirational quote that is not inspiring at all",
    "The worst thing a waiter can say after you order",
    "A board game nobody wants to play",
    "What squirrels are really burying",
    "The worst name for a newborn baby",
    "A terrible first line for a novel",
    "The real reason the chicken crossed the road",
    "What your cat does when you leave for work",
    "The worst possible school field trip",
    "A job title that sounds made up",
    "The worst thing to say on a video call before you realise you're unmuted",
    "What's really in the Bermuda Triangle",
    "A tourist attraction nobody visits twice",
    "A terrible opening line for a TED talk",
    "The worst thing to find under your bed",
    "A rejected emoji",
    "An app notification you never want to see",
    "The worst thing to say to a police horse",
    "A reality TV show that should be cancelled immediately",
    "What the Mona Lisa is actually smiling about",
    "The worst item to pack for a beach holiday",
    "A new flavour of crisps that failed spectacularly",
    "The worst thing your landlord can text you",
    "A very specific phobia",
    "What aliens think the pyramids were for",
    "A terrible name for a hair salon",
    "The worst advice a grandparent ever gave",
    "An awkward thing to say in a lift",
    "The worst name for a restaurant",
    "What the tooth fairy does with all those teeth",
    "A terrible prize at a school raffle",
    "What your laptop fan is trying to tell you",
    "A sport that would be improved by adding bees",
    "The worst motivational poster for an office",
    "What your future self is texting you right now",
    "A terrible name for a political party",
    "The worst thing to say at a baby shower"
  ],
  cheeky: [
    "The least romantic thing to whisper in bed",
    "What your search history says about you",
    "A terrible pickup line for a funeral",
    "The worst thing to hear on a first date after the second drink",
    "A rejected Tinder bio",
    "What happens at the office party that stays at the office party",
    "The worst name for a lingerie brand",
    "What your ex is doing right now",
    "A walk of shame excuse that nobody believes",
    "The worst thing to accidentally send to the family group chat",
    "A drinking game that should be illegal",
    "The worst thing to find in your partner's browser history",
    "What the neighbours heard last night",
    "The worst safe word",
    "A terrible thing to moan during a massage",
    "Something you should never say during a hangover brunch",
    "The worst thing to say right after a kiss",
    "A cocktail name that should get the bartender fired",
    "The real reason for the stag do disaster",
    "What your mum found in your room",
    "A hen party activity that went too far",
    "The worst thing to hear through hotel walls",
    "An honest name for a nightclub",
    "What the bouncer is really thinking",
    "The worst excuse for not texting back",
    "A dating app filter that really should exist",
    "The worst place to get caught skinny dipping",
    "What really goes on at a book club",
    "The worst thing to say to a date's roommate at 7 a.m.",
    "A flirting technique that has never once worked"
  ],
  finals: [
    "The title of your future autobiography",
    "What aliens will write in their report about humans",
    "The secret ingredient in grandma's famous recipe",
    "The first rule of the group chat",
    "Your honest review of this game night",
    "What will be written on your tombstone",
    "The name of your future pub",
    "The worst thing to hear from the person next to you on a 12-hour flight",
    "The headline if you became famous tomorrow",
    "A confession you'd make only on your last day on Earth",
    "The fourth wise man's gift",
    "Your villain origin story in one sentence",
    "What you would ban if you ruled the world for a day",
    "The last text you'd send before the zombie apocalypse",
    "Your warning label",
    "The name of the documentary about your life"
  ]
};

/* Nederlandse vragen. Geen letterlijke vertaling: waar een grap op een Engelse referentie leunt, staat hier een Nederlandse. */
window.ZINGERS_PROMPTS_NL = {
  clean: [
    "Een slechte naam voor een bejaardentehuis",
    "De echte reden dat de dinosaurussen uitstierven",
    "Wat je kamerplant achter je rug over je zegt",
    "Het ergste om in de la van een hotelkamer te vinden",
    "Een afgekeurde smaak tandpasta",
    "De recensie van één ster die een spook achterlaat voor de Efteling",
    "Iets wat je nooit moet fluisteren tijdens een sollicitatiegesprek",
    "Waar katten stiekem mee bezig zijn",
    "De slechtst mogelijke slogan voor de NS",
    "Een nieuwe Olympische sport waar niemand om vroeg",
    "Het minst geruststellende wat een chirurg halverwege de operatie kan zeggen",
    "Een slecht thema voor een kinderfeestje",
    "De kleine lettertjes van een goedkoop sportschoolabonnement",
    "Een nutteloze spreuk op een scheurkalender",
    "De slechtst mogelijke trouwgelofte",
    "Een superheld met een extreem specifieke superkracht",
    "Het meest verdachte om om 3 uur 's nachts bij de nachtwinkel te kopen",
    "Een zelfhulpboek dat alles alleen maar erger maakt",
    "Het slechtste excuus om te laat te komen op je eigen bruiloft",
    "Wat je koelkast zou zeggen als hij kon praten",
    "Een wet waar maar één heel specifiek persoon iets aan heeft",
    "Het laatste wat je van je therapeut wilt horen",
    "Een afgekeurde naam voor een nieuw ontdekte planeet",
    "Een appje dat je nooit naar je baas moet sturen",
    "Wat de printer op kantoor écht denkt",
    "Het ergste wat een gids kan zeggen in de Keukenhof",
    "Een geurkaars die niet zou mogen bestaan",
    "De echte reden dat de buren een deurbelcamera hebben",
    "Een slechte naam voor een meditatie-app",
    "Waar duiven het over hebben op hun wekelijkse vergadering",
    "Het ergste om te zeggen als je voor het eerst je schoonouders ontmoet",
    "Een LinkedIn-vaardigheid die niemand zou moeten onderschrijven",
    "De slechtst mogelijke afwezigheidsmelding",
    "Het wifi-wachtwoord van een heel ongastvrij café",
    "Een functie die je telefoon echt niet nodig heeft",
    "De echte reden dat deze vergadering ook een mailtje had kunnen zijn",
    "Een slechte naam voor een boot",
    "Het slechtste om mee te nemen naar een kringverjaardag",
    "Een afgekeurde Pixar-film",
    "Wat je hond op z'n cv zou zetten",
    "Het ergste om uit de cockpit te horen",
    "Een HEMA-product dat nooit in de schappen had mogen liggen",
    "Het minst geruststellende bordje bij een achtbaan",
    "De slechtst mogelijke naam voor een datingapp",
    "Een nieuwe feestdag die niemand zou vieren",
    "Het meest passief-agressieve briefje op de gedeelde koelkast",
    "Een vervolg dat nooit gemaakt had mogen worden",
    "Waar een goudvis aan denkt tijdens z'n geheugen van drie seconden",
    "Het ergste om te roepen tijdens een stilteretraite",
    "Een misdaad die zou moeten bestaan maar het niet doet",
    "De slechtste reden om je ziek te melden",
    "Een slecht motto voor een ziekenhuis",
    "Wat je navigatie zegt als hij er helemaal klaar mee is",
    "Het ergste wat een goochelaar uit z'n hoed kan halen",
    "Een autocorrectie die een uitvaart verpestte",
    "Een nutteloos voorwerp in een noodpakket",
    "Het ergste wat je van je kapper kunt horen",
    "Het geheime ingrediënt van de kroket uit de muur",
    "Een nieuwe kleur kleurpotlood voor teleurgestelde kinderen",
    "Het saaiste superheldenverhaal ooit",
    "Wat de maan eigenlijk van ons vindt",
    "De slechtste naam voor een parfum",
    "Wat je slimme speaker hoort als je niet thuis bent",
    "Een slechte titel voor een kinderboek",
    "De echte reden dat er sokken verdwijnen in de was",
    "Een slechte vraag op een eerste date",
    "Het ergste om in je broodje shoarma te vinden",
    "Een nieuwe regel voor de kantoorkeuken",
    "Iets waar een piraat over zou klagen op social media",
    "Het slechtste liedje om op een uitvaart te draaien",
    "Waar robots zich over 100 jaar voor zullen schamen",
    "Een slechte naam voor een band van boekhouders",
    "Het ergste om te zeggen tijdens een grafrede",
    "De slechtst mogelijke tekst op een deurmat",
    "Een start-up die echt geen investering zou moeten krijgen",
    "Het ergste om op je voorhoofd te laten tatoeëren",
    "Het ene wat je nooit op je werk moet googelen",
    "Een snack die alleen een schurk zou eten",
    "Het ergste geluid tijdens een massage",
    "Hoe de groepsapp heet waar jij niet in zit",
    "Een inspirerende quote die totaal niet inspireert",
    "Het ergste wat een ober kan zeggen nadat je besteld hebt",
    "Een bordspel dat niemand wil spelen",
    "Wat eekhoorns écht begraven",
    "De slechtste naam voor een baby",
    "Een slechte eerste zin voor een roman",
    "De echte reden dat de kip overstak",
    "Wat je kat doet als jij naar je werk gaat",
    "Het slechtst mogelijke schoolreisje",
    "Een functietitel die verzonnen klinkt",
    "Het ergste om te zeggen in een videocall voor je doorhebt dat je microfoon aanstaat",
    "Wat er echt in de Bermudadriehoek zit",
    "Een toeristische attractie waar niemand twee keer heen gaat",
    "Een slechte openingszin voor een TED-talk",
    "Het ergste om onder je bed te vinden",
    "Een afgekeurde emoji",
    "Een pushmelding die je nooit wilt krijgen",
    "Het ergste om tegen een politiepaard te zeggen",
    "Een realityshow die direct van de buis moet",
    "Waar het Meisje met de parel eigenlijk naar kijkt",
    "Het slechtste om in te pakken voor een strandvakantie",
    "Een nieuwe chipssmaak die spectaculair flopte",
    "Het ergste appje dat je huisbaas kan sturen",
    "Een heel specifieke fobie",
    "Waarvoor aliens denken dat de Deltawerken dienen",
    "Een slechte naam voor een kapsalon",
    "Het slechtste advies dat een opa of oma ooit gaf",
    "Iets ongemakkelijks om te zeggen in de lift",
    "De slechtste naam voor een restaurant",
    "Wat de tandenfee doet met al die tanden",
    "Een slechte hoofdprijs bij de bingo in het buurthuis",
    "Wat de ventilator van je laptop je probeert te vertellen",
    "Een sport die beter wordt als je er bijen aan toevoegt",
    "De slechtste motivatieposter voor op kantoor",
    "Wat je toekomstige ik je nu appt",
    "Een slechte naam voor een politieke partij",
    "Het ergste om te zeggen op kraamvisite",
    "De echte reden dat de trein wéér vertraging heeft",
    "Wat Sinterklaas écht in zijn grote boek schrijft",
    "Een nieuwe smaak hagelslag waar niemand op zit te wachten",
    "Het ergste om te horen in de kring op een verjaardag",
    "Wat de Belastingdienst stiekem allemaal over jou weet",
    "Een gloednieuwe traditie voor Koningsdag",
    "Het ergste om naar iemand te roepen op het fietspad",
    "Een afgekeurde naam voor een nieuwe Hollandse snack",
    "Het slechtste Tikkie om te ontvangen",
    "Wat er écht in de erwtensoep zit",
    "Een excuus om niet naar de verjaardag van je tante te gaan",
    "Het ergste om te vinden in je boodschappenbezorging",
    "Een opdracht in Wie is de Mol? die niemand haalt",
    "Wat een meeuw van je patatje oorlog vindt",
    "De slechtste plek voor een fietsenstalling",
    "Een nieuwe regel voor Nederlanders op een Franse camping",
    "Wat je collega écht bedoelt met 'even sparren'"
  ],
  cheeky: [
    "Het minst romantische om in bed te fluisteren",
    "Wat je zoekgeschiedenis over je zegt",
    "Een slechte versierzin op een uitvaart",
    "Het ergste om te horen op een eerste date na het tweede drankje",
    "Een afgekeurde Tinder-bio",
    "Wat er op de kantoorborrel gebeurt en daar ook blijft",
    "De slechtste naam voor een lingeriemerk",
    "Waar je ex nu mee bezig is",
    "Een excuus voor je walk of shame dat niemand gelooft",
    "Het ergste om per ongeluk in de familie-app te sturen",
    "Een drankspelletje dat verboden zou moeten worden",
    "Het ergste om in de browsergeschiedenis van je partner te vinden",
    "Wat de buren vannacht hoorden",
    "Het slechtste safeword",
    "Iets ongemakkelijks om te kreunen tijdens een massage",
    "Iets wat je nooit moet zeggen bij de katerbrunch",
    "Het ergste om te zeggen vlak na een zoen",
    "Een cocktailnaam waarvoor de barman ontslagen wordt",
    "De echte reden dat het vrijgezellenfeest uit de hand liep",
    "Wat je moeder in je kamer vond",
    "Een activiteit op een vrijgezellenfeest die te ver ging",
    "Het ergste om door de muren van een hotel te horen",
    "Een eerlijke naam voor een nachtclub",
    "Wat de uitsmijter écht denkt",
    "Het slechtste excuus om niet terug te appen",
    "Een filter voor datingapps dat echt zou moeten bestaan",
    "De slechtste plek om betrapt te worden bij naaktzwemmen",
    "Wat er écht gebeurt bij een leesclub",
    "Het ergste om om 7 uur 's ochtends tegen de huisgenoot van je date te zeggen",
    "Een flirttechniek die nog nooit heeft gewerkt",
    "Wat er met carnaval gebeurt en in Brabant blijft",
    "Het ergste om tegen je date te zeggen in de rij bij de FEBO"
  ],
  finals: [
    "De titel van je toekomstige autobiografie",
    "Wat aliens in hun rapport over mensen schrijven",
    "Het geheime ingrediënt in oma's beroemde recept",
    "De eerste regel van de groepsapp",
    "Jouw eerlijke recensie van deze spelavond",
    "Wat er op je grafsteen komt te staan",
    "De naam van jouw toekomstige kroeg",
    "Het ergste om van je buurman te horen tijdens een vlucht van 12 uur",
    "De krantenkop als je morgen beroemd wordt",
    "Een bekentenis die je alleen op je laatste dag op aarde doet",
    "Het cadeau van de vierde wijze uit het oosten",
    "Jouw schurkenverhaal in één zin",
    "Wat je zou verbieden als je één dag de baas van Nederland was",
    "Het laatste appje voor de zombie-apocalyps",
    "Jouw waarschuwingsetiket",
    "De naam van de documentaire over jouw leven",
    "De eerste regel van het sinterklaasgedicht over jou"
  ]
};
